# Generated by Django 3.0.8 on 2020-07-30 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_media', models.IntegerField(choices=[(1, 'Instagram'), (2, 'Facebook')], default=1, verbose_name='Социальная сеть')),
                ('url', models.URLField(max_length=1000, verbose_name='Ссылка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('added_to_gs', models.BooleanField(default=False, verbose_name='Статус добавления в Google таблицы')),
                ('public_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='core.PublicPage', verbose_name='Публичная страница')),
            ],
            options={
                'verbose_name': 'Публикация',
                'verbose_name_plural': 'Публикации',
                'ordering': ['-created_at'],
            },
        ),
    ]
